services:
  input-provider:
    build:
      context: ../
      dockerfile: file_based_energy_pipeline/services/input_provider/Dockerfile
    ports:
      - "18081:8080"
    environment:
      - PORT=8080
      - SERVICE_API_KEY=${SERVICE_API_KEY:-}

  data-generator:
    build:
      context: ../
      dockerfile: file_based_energy_pipeline/services/data_generator/Dockerfile
    ports:
      - "18082:8080"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=8080
      - SERVICE_API_KEY=${SERVICE_API_KEY:-}

  data-analyzer:
    build:
      context: ../
      dockerfile: file_based_energy_pipeline/services/data_analyzer/Dockerfile
    ports:
      - "18083:8080"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=8080
      - SERVICE_API_KEY=${SERVICE_API_KEY:-}

  report-generator:
    build:
      context: ../
      dockerfile: file_based_energy_pipeline/services/report_generator/Dockerfile
    ports:
      - "18084:8080"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=8080
      - SERVICE_API_KEY=${SERVICE_API_KEY:-}

networks:
  default:
    name: ai-effect-services
    external: true