# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import human_ai_interaction_testing_pb2 as human__ai__interaction__testing__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in human_ai_interaction_testing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HumanAIInteractionTestingServiceStub(object):
    """---------------------------------------------------------------------------
    Service definition
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartHumanAISession = channel.unary_unary(
                '/dutch.human_ai_interaction_testing.HumanAIInteractionTestingService/StartHumanAISession',
                request_serializer=human__ai__interaction__testing__pb2.HumanAISessionSpec.SerializeToString,
                response_deserializer=human__ai__interaction__testing__pb2.StartSessionResponse.FromString,
                _registered_method=True)
        self.GetSessionStatus = channel.unary_unary(
                '/dutch.human_ai_interaction_testing.HumanAIInteractionTestingService/GetSessionStatus',
                request_serializer=human__ai__interaction__testing__pb2.SessionStatusRequest.SerializeToString,
                response_deserializer=human__ai__interaction__testing__pb2.SessionStatusResponse.FromString,
                _registered_method=True)
        self.GetSessionResult = channel.unary_unary(
                '/dutch.human_ai_interaction_testing.HumanAIInteractionTestingService/GetSessionResult',
                request_serializer=human__ai__interaction__testing__pb2.SessionResultRequest.SerializeToString,
                response_deserializer=human__ai__interaction__testing__pb2.SessionResultResponse.FromString,
                _registered_method=True)


class HumanAIInteractionTestingServiceServicer(object):
    """---------------------------------------------------------------------------
    Service definition
    ---------------------------------------------------------------------------
    """

    def StartHumanAISession(self, request, context):
        """Start a new human-AI interaction testing session.
        Launches InteractiveAI and hmisurveys as separate containers.
        Returns immediately with session_id, gui_url, and survey_url; the session runs async.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionStatus(self, request, context):
        """Poll the phase of a running session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionResult(self, request, context):
        """Retrieve results once the session has reached COMPLETED.
        Returns a gRPC error if the session is not yet complete.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HumanAIInteractionTestingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartHumanAISession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartHumanAISession,
                    request_deserializer=human__ai__interaction__testing__pb2.HumanAISessionSpec.FromString,
                    response_serializer=human__ai__interaction__testing__pb2.StartSessionResponse.SerializeToString,
            ),
            'GetSessionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionStatus,
                    request_deserializer=human__ai__interaction__testing__pb2.SessionStatusRequest.FromString,
                    response_serializer=human__ai__interaction__testing__pb2.SessionStatusResponse.SerializeToString,
            ),
            'GetSessionResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionResult,
                    request_deserializer=human__ai__interaction__testing__pb2.SessionResultRequest.FromString,
                    response_serializer=human__ai__interaction__testing__pb2.SessionResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dutch.human_ai_interaction_testing.HumanAIInteractionTestingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dutch.human_ai_interaction_testing.HumanAIInteractionTestingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HumanAIInteractionTestingService(object):
    """---------------------------------------------------------------------------
    Service definition
    ---------------------------------------------------------------------------
    """

    @staticmethod
    def StartHumanAISession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dutch.human_ai_interaction_testing.HumanAIInteractionTestingService/StartHumanAISession',
            human__ai__interaction__testing__pb2.HumanAISessionSpec.SerializeToString,
            human__ai__interaction__testing__pb2.StartSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dutch.human_ai_interaction_testing.HumanAIInteractionTestingService/GetSessionStatus',
            human__ai__interaction__testing__pb2.SessionStatusRequest.SerializeToString,
            human__ai__interaction__testing__pb2.SessionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dutch.human_ai_interaction_testing.HumanAIInteractionTestingService/GetSessionResult',
            human__ai__interaction__testing__pb2.SessionResultRequest.SerializeToString,
            human__ai__interaction__testing__pb2.SessionResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
